# Generated by Django 4.0 on 2023-04-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='links',
        ),
        migrations.AddField(
            model_name='artist',
            name='artstation_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='behance_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='deviantart_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='other_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='pinterest_page_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='pixiv_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='tumblr_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='weibo_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='pinterest_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
