# Generated by Django 4.0 on 2023-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_boards_remove_artist_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='serial_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
